services:
  nuxt-static:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    restart: unless-stopped
    # Optional: name the container
    container_name: nuxt_abrikosio
    volumes:
      - ./docker-nginx:/etc/nginx/conf.d
